In [1]:
from cProfile import label
from operator import index
import string
from turtle import title
from wsgiref.simple_server import sys_version
import SimpleITK as sitk
import numpy as np
import numpy.ma as ma
from matplotlib import pyplot
import matplotlib.pyplot as plt
import os
import sys
import pandas as pd

In [7]:
url = "D:\\Aaron\\ProstateMRL\\Data\\Extraction\\Mean_values\\Raw\\Datafiles\\SABR.csv"
df_all = pd.read_csv(url)
df_all

,Unnamed: 0,PatID,ScanDate,Scan,Observer,Region,Mean,Std
0,0,653,2011-12-11,14,AR,Muscle,12.864275,101.607449
1,1,653,2011-12-11,14,MA,Prostate,73.363194,48.221969
2,2,653,2011-12-11,15,AR,Muscle,12.242907,102.072372
3,3,653,2011-12-11,15,MA,Prostate,85.214354,50.432136
4,4,653,2011-12-11,15,RP,Prostate,84.693648,48.518564
...,...,...,...,...,...,...,...,...
203,203,1464,2012-11-16,3,RP,Prostate,67.817481,33.207976
204,204,1464,2012-11-18,4,AR,Muscle,23.722927,96.372541
205,205,1464,2012-11-18,4,RP,Prostate,74.356370,31.464275
206,206,1464,2012-11-21,5,AR,Muscle,26.337477,92.730564
207,207,1464,2012-11-21,5,RP,Prostate,65.374372,31.084056

In [8]:
patIDs = df_all.PatID.unique

df_all["ScanDate"] = pd.to_datetime(df_all["ScanDate"], dayfirst=True)

df_all.head()

,Unnamed: 0,PatID,ScanDate,Scan,Observer,Region,Mean,Std
0,0,653,2011-12-11,14,AR,Muscle,12.864275,101.607449
1,1,653,2011-12-11,14,MA,Prostate,73.363194,48.221969
2,2,653,2011-12-11,15,AR,Muscle,12.242907,102.072372
3,3,653,2011-12-11,15,MA,Prostate,85.214354,50.432136
4,4,653,2011-12-11,15,RP,Prostate,84.693648,48.518564

In [49]:
patIDs = df_all.PatID.unique()
patIDs = [653]
print(patIDs)
#numPat = patIDs.size()

for i in patIDs:
    pat = [str(i)]
    pat_df = df_all.loc[pat]
    #pat_df = df_all[df_all["PatID"].isin([i])]

    #print(pat_df.head())

    firstScan = pat_df["ScanDate"].min()
    pat_df["DaysFromFrac1"] = pat_df["ScanDate"] - firstScan
    pat_df["DaysFromFrac1"] = pd.to_numeric(pat_df["DaysFromFrac1"].dt.days, downcast="integer")
    pat_df = pat_df.sort_values(by=["DaysFromFrac1"])

    print(pat_df.tail())

[653]

KeyError: "None of [Index(['653'], dtype='object')] are in the [index]"